server:
  port: 9093
  servlet:
    context-path: /manager

spring:
  #文件上传服务
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #数据源设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: choco
    password: 111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000

  # Redis配置
  redis:
    timeout: 10000ms                        # 连接超时时间
    host: 114.215.183.44                   # Redis服务器地址
    port: 6379                              # Redis服务器端口
    database: 0                             # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024                    # 最大连接数，默认 8
        max-wait: 10000ms                   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200                       # 最大空闲连接，默认 8
        min-idle: 5

  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    enabled: true
    # 模板引擎加载资源位置
    template-loader-path: classpath:/templates/
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    expose-session-attributes: true
    request-context-attribute: request
    # 是否可以直接获取请求接口里面的熟悉
    settings:
      classic_compatible: true
      # 配置标签语法为自动, 把<>变为[], 区分html
      tag_syntax: auto_detect
      # 模板更新时间
      template_update_delay: 0
      default_encoding: UTF-8
      output_encoding: UTF-8
      # 本地化
      locale: zh_CN
      date_format: yyyy-MM-dd
      # 数字格式化
      number_format: #.##
      # boolean格式化
      boolean_format: true,false
      template_exception_handler: html_debug
    suffix: .ftl

#dubbo配置
dubbo:
  application:
    name: manager-consumer
  registry:
    address: zookeeper://114.215.183.44:2181?backup=114.215.183.44:2182,114.215.183.44:2183
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.choco.manager

# mybatis配置
mybatis:
  type-aliases-package: com.choco.manager.entity
  mapper-locations: classpath:/com/choco/manager/mapper/*.xml

logging:
  level:
    com.choco.manager.mapper: debug
# Redis Key
# 商品分类列表 Key
goods.category.list.key: goods:category:list:goodsCategoryList
#用户票据key
user.ticket: user:userTicket

























